package e50;

import android.os.Parcel;
import kotlin.NotImplementedError;
import m80.k;

/* compiled from: r8-map-id-edd0706d8ade6e5fa050dcf48a624fb4468a151a6c9a3ed423de0572ab36a89c */
/* loaded from: classes8.dex */
public interface f<T> {

    /* compiled from: r8-map-id-edd0706d8ade6e5fa050dcf48a624fb4468a151a6c9a3ed423de0572ab36a89c */
    public static final class a {
        @k
        public static <T> T[] a(@k f<T> fVar, int i11) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    T a(@k Parcel parcel);

    void b(T t11, @k Parcel parcel, int i11);

    @k
    T[] newArray(int i11);
}
